### ISSUE TITLE
 InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by mekbib-tekle** [ningsuhen/passport-linkedin-token#5]
InternalOAuthError: failed to fetch user profile
       at /usr/src/app/node_modules/passport-linkedin-token/lib/passport-linkedin-token/strategy.js:140:28
       at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth.js:397:13)
       at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth.js:409:9)
       at IncomingMessage.emit (events.js:187:15)
       at endReadableNT (_stream_readable.js:1094:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by codeocelot** [comment]
At the peril of responding to a year old post, @Mekbib-awono did you ever find a solution to this?

**Comment by luisfranciscocesar** [comment]
Sigue el mismo problema, recomiendo no usar la libreria.  no tiene soporte tampoco

**Comment by patomation** [comment]
At the peril of responding to a 3 year old post, I would also like to know the solution to this
